# Generated by Django 6.0 on 2025-12-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='conversation',
            name='role',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='session_id',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
